/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfst2023.handins;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) throws Exception {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        try {
            Parent root = FXMLLoader.load(getClass().getResource("views/main.fxml"));
            primaryStage.setTitle("Map parser");
            primaryStage.getIcons().add(new Image(getClass().getResource("images/logo.png").toURI().toString()));
            primaryStage.setScene(new Scene(root, 600, 400));
            primaryStage.show();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}