/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfst2023.handins;

import org.junit.jupiter.api.Test;

import bfst2023.handins.Model.Address;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        
    }

    @Test
    void simple() {

    }

}
